### ISSUE TITLE
Failed to open event 1: No such file or directory.  when using Cirron

### ISSUE THREAD

**Issue by laithsakka** [s7nfo/Cirron#14]
We are trying to use Cirron to collect builds benchmarks on pytroch CI.
and we are hitting the error.
Failed to open event 1: No such file or directory. 

 the test runs within a docker container not sure if that could be related. 
 any hints on what files could be missing?
```
python benchmarks/dynamo/pr_time_benchmarks/benchmarks/update_hint_benchmark.py
Failed to open event 1: No such file or directory.
Traceback (most recent call last):
  File "benchmarks/dynamo/pr_time_benchmarks/benchmarks/update_hint_benchmark.py", line 45, in <module>
    main()
  File "benchmarks/dynamo/pr_time_benchmarks/benchmarks/update_hint_benchmark.py", line 41, in main
    print(P0().enable_instruction_count().collect_all())
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/benchmarks/dynamo/pr_time_benchmarks/benchmark_base.py", line 47, in collect_all
    result.append((self.name(), "instruction_count", self.count_instructions()))
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/benchmarks/dynamo/pr_time_benchmarks/benchmark_base.py", line 37, in count_instructions
    with Collector() as collector:
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/cirron/cirron.py", line 67, in _init_
    with Collector(measure_overhead=False) as collector:
  File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/cirron/cirron.py", line 81, in _enter_
    raise Exception(
Exception: Failed to start collector. Make sure you have the right permissions, you might need to use sudo.
```

The code is simple 
https://github.com/pytorch/pytorch/pull/131475
```
lass Benchmark(ABC):
    _instruction_count = False

    def enable_instruction_count(self):
        self._instruction_count = True
        return self

    def name(self):
        return ""

    def description(self):
        return ""

    def reset(self):  # noqa: B027
        pass

    @abstractmethod
    def prepare(self):
        pass

    @abstractmethod
    def work(self):
        pass

    def count_instructions(self):
        self.reset()
        self.prepare()
        results = []
        for i in range(10):
            self.reset()
            self.prepare()
            with Collector() as collector:
                self.work()

            if i != 0:
                results.append(collector.counters.instruction_count)
        return min(results)

    def collect_all(self):
        result = []
        if self._instruction_count:
            result.append((self.name(), "instruction_count", self.count_instructions()))
        return result
   ```

**Comment by s7nfo** [comment]
First thing I'd try is to make sure the process executing Cirron has the right permission to execute `perf_event_open`, like the error message suggests.

If it does and it still doesn't work, maybe try running `perf list hw`. If that works and the list includes instruction count, it's probably a bug in Cirron, if it does not, then the system doesn't provide hardware counters for some reasons. AFAIK Docker by itself should not prevent access to them, so maybe your image can be configured differently?

FWIW the GitHub Actions Ubuntu Image for example does not support `perf_event_open`, so I had to disable tests for Collector on it: https://github.com/s7nfo/Cirron/blob/master/python/tests/tests.py#L22
Related issue: https://github.com/actions/runner-images/issues/4974

**Comment by laithsakka** [comment]
this end being related to amazon machine not supporting access to perf counters i switched to amz2023.linux.12xlarge machine and it worked

**Comment by laithsakka** [comment]
I wonder if we can test for hardware counter access and print something like
"this machine does not have access to hardware counters"

**Comment by s7nfo** [comment]
That's great to hear! Let me know if you miss any features.

> I wonder if we can test for hardware counter access and print something like
"this machine does not have access to hardware counters"

I'm not sure if I can distinguish between insufficient permissions and the machine not having access, but I'll look into it. At the very least I can mention this possibility in the error message.

**Comment by laithsakka** [comment]
thanks!
