### ISSUE TITLE
Collector and tracer could be context managers?

### ISSUE THREAD

**Issue by kinow** [s7nfo/Cirron#3]
e.g. https://realpython.com/python-with-statement/#coding-class-based-context-managers

So that instead of

```py
t = Tracer()
t.start()
# ....
t.end() # or stop/etc
```

one could use

```py
with Tracer(): # or tracer/start_trace/etc
  # ...
```

simplifying the code a bit and avoiding confusion with closing function names.

**Comment by s7nfo** [comment]
I considered that, but I thought the context manager object (the `t` in the code below) only lives within the `with` scope, which would have made it a little awkward.

```
with Tracer() as t:
   (...)
```

I checked and I was wrong! So this is definitely much nicer.

PR here: https://github.com/s7nfo/Cirron/pull/6

**Comment by kinow** [comment]
Thank you!
